services:

  ghostport-relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghostport-relay
    restart: always
    env_file:
      - .env
    expose:
      - 2080
    ports:
      - ${GHOSTPORT_LOCAL_FORWARD_PORT}:2080
    command: ghostport-relay.sh
    healthcheck:
      test: ["CMD", "netstat", "-tln", "|", "grep", ":2080"]
      interval: 20s
      timeout: 10s
      retries: 5

  ghostport-endpoint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghostport-endpoint
    restart: always
    depends_on:
      ghostport-relay:
        condition: service_healthy
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    command: ghostport-endpoint.sh
    healthcheck:
      test: ["CMD", "pgrep", "autossh"]
      interval: 20s
      timeout: 10s
      retries: 5